version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
volumes:
  mysql_data:
    driver: local
